# 站点设置(jekyll自带)
permalink: /:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "code"]
paginate: 8
timezone: Asia/Shanghai
excerpt_separator: "<!-- more -->"
plugins:
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge

# 站点设置(个人)
disqus_show_comment_count: true
disqus_short_name: guozengxin
recently_posts_limit: 6
related_posts_limit: 6
google_tracking_id: 'UA-48443270-1'


# 站点链接设置
url : http://guozengxin.com
BASE_PATH : false
ASSET_PATH : /assets
archive_path: /archive/
categories_path : /categories/
about_path : /about/
tags_path : /tags/
rss_path : /rss.xml
atom_path : /atom.xml

# 个人信息
title : "Xiaoxin's Blog"
tagline: KEEP THINKING
description: 技术博客, 个人博客
author :
  name : guozengxin
  site : 
  email : 
  github : guozengxin
  weibo: xdxiaoxin

# 站点分析
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-48443270-1'
  getclicky :
    site_id : 
  mixpanel :
    token : '_MIXPANEL_TOKEN_'
  piwik :
    baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
    idsite : '1'                   # the id of the site on Piwik
