permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "code"]
highlighter: pygments
paginate: 8
markdown: kramdown
timezone: Asia/Shanghai


title : "Xiaoxin's Blog"
tagline: KEEP THINKING
description: 技术博客, 个人博客


author :
  name : xiaoxin
  email : 
  github : guozengxin
  weibo: xdxiaoxin

production_url : http://blog.guozengxin.cn

BASE_PATH : false
ASSET_PATH : /assets

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
rss_path : /rss.xml
atom_path : /atom.xml

#一些设置
index: true

disqus_show_comment_count: true
comments :
  provider : disqus
  disqus :
    short_name : guozengxin
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
   
analytics :
  provider : google 
  google : 
    tracking_id : 'UA-48443270-1'
  getclicky :
    site_id : 
  mixpanel :
    token : '_MIXPANEL_TOKEN_'
  piwik :
    baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
    idsite : '1'                   # the id of the site on Piwik
